Updated copy and paste scripts

diff --git a/bin/.local/bin/copy b/bin/.local/bin/copy
--- a/bin/.local/bin/copy
+++ b/bin/.local/bin/copy
@@ -1,14 +1,17 @@
-#!/bin/sh
-# Quick shortcut to platform specific copy
-source dotfiles
+#!/usr/bin/env bash
+set -e
+set -u
+set -o pipefail
 
-if is_ubuntu; then
-  COMMAND='xclip -selection clipboard'
-  alias paste='xclip -selection clipboard -o'
-elif is_osx; then
-  COMMAND='pbcopy'
-elif is_win; then
-  COMMAND='/dev/clipboard'
+if hash pbcopy 2>/dev/null; then
+  cmd='pbcopy'
+elif hash wl-copy 2>/dev/null; then
+  cmd='wl-copy'
+elif hash xclip 2>/dev/null; then
+  cmd='xclip -selection clipboard'
+else
+  echo 'cannot find a copy program' >&2
+  exit 1
 fi
 
-exec "$COMMAND"
+exec perl -pe 'chomp if eof' | $cmd
diff --git a/bin/.local/bin/paste b/bin/.local/bin/paste
--- a/bin/.local/bin/paste
+++ b/bin/.local/bin/paste
@@ -1,13 +1,15 @@
-#!/bin/sh
-# Quick shortcut to platform specific copy
-source dotfiles
+#!/usr/bin/env bash
+set -e
+set -u
+set -o pipefail
 
-if is_ubuntu; then
-  COMMAND='xclip -selection clipboard -o'
-elif is_osx; then
-  COMMAND='pbpaste'
-elif is_win; then
-  COMMAND='cat /dev/clipboard'
+if hash pbpaste 2>/dev/null; then
+  exec pbpaste
+elif hash wl-paste 2>/dev/null; then
+  exec wl-paste
+elif hash xclip 2>/dev/null; then
+  exec xclip -selection clipboard -o
+else
+  echo 'cannot find a paste program' >&2
+  exit 1
 fi
-
-exec "$COMMAND"
