Added input validation & path correct to todo script

diff --git a/bin/.local/bin/todo b/bin/.local/bin/todo
--- a/bin/.local/bin/todo
+++ b/bin/.local/bin/todo
@@ -2,6 +2,11 @@
 # A script to create org mode todo on command line
 SED=sed
 
+if [ -z "$1" ]; then
+    echo "Input required"
+    exit 1
+fi
+
 if [ "$(uname)" == "Darwin" ]; then
     SED=gsed
 fi
@@ -9,7 +14,7 @@ fi
 if [ "$1" == "-w" ]; then
     shift
     $SED --in-place 's/^\(* Work .*\)$/\1\n** TODO '"$(echo ${@})"'/g' \
-        "$HOME/org/gtd.org"
+        "$HOME/org/work.org"
 else
     $SED --in-place 's/^\(* Personal .*\)$/\1\n** TODO '"$(echo ${@})"'/g' \
         "$HOME/org/gtd.org"
